name: julep-blob-store

services:
  seaweedfs:
    image: julepai/blob-store:${TAG:-dev}
    build:
      context: .
      dockerfile: Dockerfile
    profiles:
      - blob-store

    environment:
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - DEBUG=${DEBUG:-false}

    ports:
      - 9333:9333  # master port
      - 8333:8333  # s3 port
      - 8888:8888  # filer port
      - 28080:28080  # volume port
      # - 19333:19333  # master grpc port
      # - 18081:18080  # volume grpc port
      # - 18888:18888  # filer grpc port
    command: "-volume -volume.dir.idx /data -filer -s3 -dir=/data -ip=seaweedfs -ip.bind=0.0.0.0 -metricsPort=9321 -master.raftBootstrap=false -master.port=9333 -volume.port=28080 -volume.index=leveldb -filer.port=8888 -s3.port=8333"
    healthcheck:
      test: [ "CMD", "wget", "-qSO", "-", "http://0.0.0.0:9333/cluster/healthz" ]
      interval: 60s
      retries: 6
      timeout: 60s
      start_period: 30s
      start_interval: 10s

    volumes:
      - seaweedfs_data:/data

volumes:
  seaweedfs_data:
    external: true
