name: julep-analytics

services:
  analytics:
    image: julepai/analytics:${TAG:-dev}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: julep-analytics
    profiles:
      - multi-tenant
    environment:
      # Metabase application database (for storing Metabase's own data)
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: ${METABASE_DB_PASSWORD:-metabase_secure_password}
      MB_DB_HOST: metabase-db
      
      # Metabase settings
      MB_SITE_URL: https://${JULEP_HOST:-localhost}/analytics
      MB_SITE_NAME: "Julep Analytics"
      MB_APPLICATION_NAME: "Julep Analytics"
      
      # AIDEV-NOTE: Metabase configured to use same postgres instance as agents-api
    ports:
      - "3001:3000"  # Expose on different port to avoid conflicts
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      metabase-db:
        condition: service_healthy
  
  metabase-db:
    image: postgres:latest
    container_name: julep-metabase-db
    profiles:
      - multi-tenant
    hostname: metabase-db
    restart: unless-stopped
    volumes:
      - metabase-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=metabase
      - POSTGRES_PASSWORD=${METABASE_DB_PASSWORD:-metabase_secure_password}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U metabase -d metabaseappdb']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  metabase-db-data:
    external: true
