/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const $Chat_ChatOutputChunk = {
  type: "all-of",
  description: `Streaming chat completion output`,
  contains: [
    {
      type: "Chat_BaseChatOutput",
    },
    {
      properties: {
        delta: {
          type: "all-of",
          description: `The message generated by the model`,
          contains: [
            {
              type: "Entries_InputChatMLMessage",
            },
          ],
          isRequired: true,
        },
      },
    },
  ],
} as const;
