/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as JulepApi from "..";

export interface ChatInputData {
    /** A list of new input messages comprising the conversation so far. */
    messages: JulepApi.InputChatMlMessage[];
    /** (Advanced) List of tools that are provided in addition to agent's default set of tools. Functions of same name in agent set are overriden */
    tools?: JulepApi.Tool[];
    /** Can be one of existing tools given to the agent earlier or the ones included in the request */
    toolChoice?: JulepApi.ToolChoiceOption;
}
