/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * ChatML role (system|assistant|user|function_call)
 */
export type ChatMlMessageRole = "user" | "assistant" | "system" | "function_call";

export const ChatMlMessageRole = {
    User: "user",
    Assistant: "assistant",
    System: "system",
    FunctionCall: "function_call",
} as const;
