/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * ChatML role (system|assistant|user|function_call)
 */
export declare type ChatMlMessageRole =
  | "user"
  | "assistant"
  | "system"
  | "function_call";
export declare const ChatMlMessageRole: {
  readonly User: "user";
  readonly Assistant: "assistant";
  readonly System: "system";
  readonly FunctionCall: "function_call";
};
