/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Up to 4 sequences where the API will stop generating further tokens.
 */
export type ChatSettingsStop = string | undefined | string[];
