/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as JulepApi from "..";
/**
 * Can be one of existing tools given to the agent earlier or the ones included in the request
 */
export declare type ChatInputDataToolChoice =
  | JulepApi.ToolChoiceOption
  | JulepApi.NamedToolChoice;
