/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Episode {
    type: "episode";
    /** (Optional) ID of the subject user */
    subject?: string;
    /** Content of the memory */
    content: string;
    /** Weight (importance) of the memory on a scale of 0-100 */
    weight: number;
    /** Episode created at (RFC-3339 format) */
    createdAt: Date;
    /** Episode last accessed at (RFC-3339 format) */
    lastAccessedAt: Date;
    /** Episode happened at (RFC-3339 format) */
    happenedAt: Date;
    /** Duration of the episode (in seconds) */
    duration?: number;
    /** Episode id (UUID) */
    id: string;
}
