"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.InputChatMlMessageRole = void 0;
exports.InputChatMlMessageRole = {
  User: "user",
  Assistant: "assistant",
  System: "system",
  FunctionCall: "function_call",
};
