/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface Session {
  /** Session id (UUID) */
  id: string;
  /** User ID of user associated with this session */
  userId: string;
  /** Agent ID of agent associated with this session */
  agentId: string;
  /** A specific situation that sets the background for this session */
  situation?: string;
  /** (null at the beginning) - generated automatically after every interaction */
  summary?: string;
  /** Session created at (RFC-3339 format) */
  createdAt?: Date;
  /** Session updated at (RFC-3339 format) */
  updatedAt?: Date;
}
