/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether the suggestion is for the `agent` or a `user`
 */
export type SuggestionTarget = "user" | "agent";

export const SuggestionTarget = {
    User: "user",
    Agent: "agent",
} as const;
