/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether this tool is a `function` or a `webhook` (Only `function` tool supported right now)
 */
export type ToolType = "function" | "webhook";

export const ToolType = {
    Function: "function",
    Webhook: "webhook",
} as const;
