/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as JulepApi from "..";
export interface Tool {
  /** Whether this tool is a `function` or a `webhook` (Only `function` tool supported right now) */
  type: JulepApi.ToolType;
  /** Function definition and parameters */
  function: JulepApi.FunctionDef;
  /** Tool ID */
  id: string;
}
