/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface User {
    /** Name of the user */
    name?: string;
    /** About the user */
    about?: string;
    /** User created at (RFC-3339 format) */
    createdAt?: Date;
    /** User updated at (RFC-3339 format) */
    updatedAt?: Date;
    /** User id (UUID) */
    id: string;
}
