[tasks]
format = "ruff format"
lint = "ruff check"
typecheck = "pytype --config pytype.toml"
validate-sql = "sqlvalidator --verbose-validate agents_api/"
check = [
    "lint",
    "format",
    "validate-sql",
    "typecheck",
]
codegen_openapi = """
datamodel-codegen \
  --input ../openapi.yaml \
  --input-file-type openapi \
  --output agents_api/autogen/ \
  --output-model-type pydantic_v2.BaseModel \
  --strict-types bool \
  --strict-nullable \
  --allow-population-by-field-name \
  --field-include-all-keys \
  --reuse-model \
  --snake-case-field \
  --enum-field-as-literal all \
  --field-constraints \
  --use-operation-id-as-name \
  --use-schema-description \
  --use-field-description \
  --use-annotated \
  --use-default \
  --use-unique-items-as-set \
  --use-subclass-enum \
  --use-union-operator \
  --use-one-literal-as-default \
  --use-double-quotes \
  --use-exact-imports \
  --use-standard-collections \
  --use-non-positive-negative-number-constrained-types \
  --target-python-version 3.12 \
  --treat-dot-as-module \
  --use-title-as-name \
  --collapse-root-models \
  --output-datetime-class AwareDatetime \
  --openapi-scopes schemas \
  --keep-model-order \
  --disable-timestamp"""
fix_list_response = "python -c \"import base64; exec(base64.b64decode('CmltcG9ydCByZQoKZGVmIGZpeF9nZW5lcmljX2NsYXNzZXMoZmlsZV9wYXRoKToKICAgIHdpdGggb3BlbihmaWxlX3BhdGgsICdyJykgYXMgZmlsZToKICAgICAgICBjb250ZW50ID0gZmlsZS5yZWFkKCkKCiAgICAjIFJlZ3VsYXIgZXhwcmVzc2lvbiB0byBmaW5kIGluY29ycmVjdCBnZW5lcmljIGNsYXNzIGRlZmluaXRpb25zCiAgICBwYXR0ZXJuID0gcmUuY29tcGlsZShyJ2NsYXNzIChcdyspXFsoXHcrKTogQmFzZU1vZGVsXF1cKChCYXNlTW9kZWwpXCk6JykKICAgIHJlcGxhY2VtZW50ID0gcidjbGFzcyBcMShcMywgR2VuZXJpY1tcMl0pOicKCiAgICAjIFJlcGxhY2UgaW5jb3JyZWN0IGdlbmVyaWMgY2xhc3MgZGVmaW5pdGlvbnMKICAgIGZpeGVkX2NvbnRlbnQgPSByZS5zdWIocGF0dGVybiwgcmVwbGFjZW1lbnQsIGNvbnRlbnQpCgogICAgIyBXcml0ZSB0aGUgZml4ZWQgY29udGVudCBiYWNrIHRvIHRoZSBmaWxlCiAgICB3aXRoIG9wZW4oZmlsZV9wYXRoLCAndycpIGFzIGZpbGU6CiAgICAgICAgZmlsZS53cml0ZShmaXhlZF9jb250ZW50KQoKZml4X2dlbmVyaWNfY2xhc3NlcygnYWdlbnRzX2FwaS9hdXRvZ2VuL29wZW5hcGlfbW9kZWwucHknKQo=').decode())\""
codegen = [
    "codegen_openapi",
    "fix_list_response",
]

[tasks.test]
env = { AGENTS_API_TESTING = "true", PYTHONPATH = "{PYTHONPATH}:." }
cmd = "ward test --exclude .venv"
