/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Specifying a particular function via `{"name": "my_function"}` forces the model to call that function.
 */
export interface FunctionCallOption {
    /** The name of the function to call. */
    name: string;
}
