name: pgai
services:
  memory-store:
    image: timescale/timescaledb-ha:pg17.6-ts2.22.1-all

    environment:
      - POSTGRES_PASSWORD=${MEMORY_STORE_PASSWORD:-julep_secure_password}
      - OPENAI_API_KEY=${OPENAI_API_KEY:?OPENAI_API_KEY is required}
    ports:
      - "5432:5432"
    volumes:
      - memory_store_data:/home/postgres/pgdata/data

    # TODO: Fix this to install pgaudit
    # entrypoint: []
    # command: >-
    #   sed -r -i "s/[#]*\s*(shared_preload_libraries)\s*=\s*'(.*)'/\1 = 'pgaudit,\2'/;s/,'/'/" /home/postgres/pgdata/data/postgresql.conf
    #   && exec /docker-entrypoint.sh

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

  vectorizer-worker:
    image: timescale/pgai-vectorizer-worker:v0.10.5
    environment:
      - PGAI_VECTORIZER_WORKER_DB_URL=postgres://postgres:${MEMORY_STORE_PASSWORD:-julep_secure_password}@memory-store:5432/postgres
      - OPENAI_API_KEY=${OPENAI_API_KEY:?OPENAI_API_KEY is required}
    command: [ "--poll-interval", "5s" ]
    depends_on:
      memory-store:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G

  migration:
    image: migrate/migrate:latest
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database", "postgres://postgres:${MEMORY_STORE_PASSWORD:-postgres}@memory-store:5432/postgres?sslmode=disable" , "up"]

    restart: "no"
    develop:
      watch:
        - path: ./migrations
          target: ./migrations
          action: sync+restart
    depends_on:
      memory-store:
        condition: service_healthy

volumes:
  memory_store_data:
    external: true
