name: julep-gateway

services:
  gateway:
    image: julepai/gateway:${TAG:-dev}
    environment:
      - GATEWAY_PORT=80
      - JWT_SHARED_KEY=${JWT_SHARED_KEY}
      - AGENTS_API_URL=${AGENTS_API_URL:-http://agents-api-multi-tenant:8080}
      - TEMPORAL_UI_PUBLIC_URL=${TEMPORAL_UI_PUBLIC_URL:-http://temporal-ui-public:8080}
      - AGENTS_API_KEY=${AGENTS_API_KEY}
      - AGENTS_API_KEY_HEADER_NAME=${AGENTS_API_KEY_HEADER_NAME:-Authorization}
      - TRAEFIK_LOG_LEVEL=${TRAEFIK_LOG_LEVEL:-INFO}
    container_name: gateway
    profiles:
      - multi-tenant
    depends_on:
      agents-api-multi-tenant:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # - 443:443
      - 127.0.0.1:80:80
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G

    command:
      # - --entrypoints.web.address=:443
      # - --entrypoints.web.http.tls.domains[0].main=dev.julep.ai
      # - --entrypoints.web.http.tls.certResolver=letsencrypt
      # - --certificatesresolvers.letsencrypt.acme.email=developers@julep.ai
      # - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # - --certificatesresolvers.letsencrypt.acme.tlschallenge=true

    volumes:
      - ./letsencrypt:/letsencrypt

    develop:
      watch:
        - action: sync+restart
          path: ./entrypoint.sh
          target: /entrypoint.sh
        - action: rebuild
          path: ./traefik.yml.template
          target: /etc/traefik/traefik.yml.template
        - action: rebuild
          path: Dockerfile
