{
 "title": "Visibility",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Task processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Visibility Task Requests Vs Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(task_requests{operation=~\"Visibility.*\"}[1m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(rate(task_errors{operation=~\"Visibility.*\"}[1m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Visibility Errors Breakdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(task_errors_discarded{operation=~\"Visibility.*\"}[1m]))",
     "legendFormat": "discarded"
    },
    {
     "expr": "sum (rate(task_errors_limit_exceeded_counter{operation=~\"Visibility.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Visibility Task By Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(task_requests{operation=~\"Visibility.*\"}[1m]))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Visibility Task Errors By Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(task_errors{operation=~\"Visibility.*\"}[1m]))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "P95 Visibility Task Attempt Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(task_attempt_bucket{operation=~\"Visibility.*\"}[1m])) by (operation, le))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Avg Visibility Task Processing Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum by (operation) (rate(task_latency_processing_sum{operation=~\"Visibility.*\"}[1m]))) / (sum by (operation) (rate(task_latency_processing_count{operation=~\"Visibility.*\"}[1m])))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "P50 Visibility Task Processing Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(task_latency_processing_bucket{operation=~\"Visibility.*\"}[1m])) by (operation, le))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "P95 Visibility Task Processing Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(task_latency_processing_bucket{operation=~\"Visibility.*\"}[1m])) by (operation, le))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Avg Visibility Task Overall Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum by (operation) (rate(task_latency_sum{operation=~\"Visibility.*\"}[1m]))) / (sum by (operation) (rate(task_latency_count{operation=~\"Visibility.*\"}[1m])))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "P50 Visibility Task Overall Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(task_latency_bucket{operation=~\"Visibility.*\"}[1m])) by (operation, le))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "P95 Visibility Task Overall Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(task_latency_bucket{operation=~\"Visibility.*\"}[1m])) by (operation, le))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Avg Visibility Task E2E Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum by (operation) (rate(task_latency_queue_sum{operation=~\"Visibility.*\"}[1m]))) / (sum by (operation) (rate(task_latency_queue_count{operation=~\"Visibility.*\"}[1m])))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "P50 Visibility Task E2E Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(task_latency_queue_bucket{operation=~\"Visibility.*\"}[1m])) by (operation, le))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "P95 Visibility Task E2E Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(task_latency_processing_bucket{operation=~\"Visibility.*\"}[1m])) by (operation, le))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Standard persistence",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Vs Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(visibility_persistence_requests{visibility_type=\"standard_visibility\"}[5m]))",
       "legendFormat": "requests"
      },
      {
       "expr": "sum (rate(visibility_persistence_errors{visibility_type=\"standard_visibility\"}[5m]))",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Errors Break Down",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(visibility_persistence_invalid_argument{visibility_type=\"standard_visibility\"}[1m]))",
       "legendFormat": "invalid argument"
      },
      {
       "expr": "sum(rate(visibility_persistence_resource_exhausted{visibility_type=\"standard_visibility\"}[1m]))",
       "legendFormat": "resource exhausted"
      },
      {
       "expr": "sum(rate(visibility_persistence_condition_failed{visibility_type=\"standard_visibility\"}[1m]))",
       "legendFormat": "condition failed"
      },
      {
       "expr": "sum(rate(visibility_persistence_timeout{visibility_type=\"standard_visibility\"}[1m]))",
       "legendFormat": "timeout"
      },
      {
       "expr": "sum(rate(visibility_persistence_not_found{visibility_type=\"standard_visibility\"}[1m]))",
       "legendFormat": "not found"
      },
      {
       "expr": "sum(rate(visibility_persistence_internal{visibility_type=\"standard_visibility\"}[1m]))",
       "legendFormat": "internal"
      },
      {
       "expr": "sum(rate(visibility_persistence_unavailable{visibility_type=\"standard_visibility\"}[1m]))",
       "legendFormat": "unavailable"
      }
     ]
    },
    {
     "title": "Requests Per Operation",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(visibility_persistence_requests{visibility_type=\"standard_visibility\"}[1m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Errors Per Operation",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(visibility_persistence_errors{visibility_type=\"standard_visibility\"}[1m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Avg Latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "(sum by (operation) (rate(visibility_persistence_latency_sum{visibility_type=\"standard_visibility\"}[1m]))) / (sum by (operation) (rate(visibility_persistence_latency_count{visibility_type=\"standard_visibility\"}[1m])))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "P50 Latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(visibility_persistence_latency_bucket{visibility_type=\"standard_visibility\"}[1m])) by (operation, le))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "P95 Latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(visibility_persistence_latency_bucket{visibility_type=\"standard_visibility\"}[1m])) by (operation, le))",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Advanced persistence (Elasticsearch)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 }
  },
  {
   "title": "Request Vs Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(visibility_persistence_requests{visibility_type=\"advanced_visibility\"}[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum (rate(visibility_persistence_errors{visibility_type=\"advanced_visibility\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Errors Break Down",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(visibility_persistence_invalid_argument{visibility_type=\"advanced_visibility\"}[1m]))",
     "legendFormat": "invalid argument"
    },
    {
     "expr": "sum(rate(visibility_persistence_resource_exhausted{visibility_type=\"advanced_visibility\"}[1m]))",
     "legendFormat": "resource exhausted"
    },
    {
     "expr": "sum(rate(visibility_persistence_condition_failed{visibility_type=\"advanced_visibility\"}[1m]))",
     "legendFormat": "condition failed"
    },
    {
     "expr": "sum(rate(visibility_persistence_timeout{visibility_type=\"advanced_visibility\"}[1m]))",
     "legendFormat": "timeout"
    },
    {
     "expr": "sum(rate(visibility_persistence_not_found{visibility_type=\"advanced_visibility\"}[1m]))",
     "legendFormat": "not found"
    },
    {
     "expr": "sum(rate(visibility_persistence_internal{visibility_type=\"advanced_visibility\"}[1m]))",
     "legendFormat": "internal"
    },
    {
     "expr": "sum(rate(visibility_persistence_unavailable{visibility_type=\"advanced_visibility\"}[1m]))",
     "legendFormat": "unavailable"
    }
   ]
  },
  {
   "title": "Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(visibility_persistence_requests{visibility_type=\"advanced_visibility\"}[1m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Errors Per Operation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(visibility_persistence_errors{visibility_type=\"advanced_visibility\"}[1m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "(sum by (operation) (rate(visibility_persistence_latency_sum{visibility_type=\"advanced_visibility\"}[1m]))) / (sum by (operation) (rate(visibility_persistence_latency_count{visibility_type=\"advanced_visibility\"}[1m])))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "P50 Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(visibility_persistence_latency_bucket{visibility_type=\"advanced_visibility\"}[1m])) by (operation, le))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(visibility_persistence_latency_bucket{visibility_type=\"advanced_visibility\"}[1m])) by (operation, le))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Elasticsearch bulk processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Requests Vs Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(elasticsearch_bulk_processor_requests{service=\"$service\"}[1m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum (rate(elasticsearch_bulk_processor_errors{service=\"$service\"}[1m])) by (http_status, le)",
     "legendFormat": "{{http_status}} errors"
    },
    {
     "expr": "sum (rate(elasticsearch_bulk_processor_retries{service=\"$service\"}[1m])) by (http_status, le)",
     "legendFormat": "{{http_status}} retryable errors"
    },
    {
     "expr": "sum (rate(elasticsearch_bulk_processor_corrupted_data{service=\"$service\"}[1m]))",
     "legendFormat": "corrupted data errors"
    },
    {
     "expr": "sum (rate(elasticsearch_bulk_processor_deadlock{service=\"$service\"}[1m]))",
     "legendFormat": "deadlock"
    },
    {
     "expr": "sum (rate(elasticsearch_bulk_processor_duplicate_request{service=\"$service\"}[1m]))",
     "legendFormat": "duplicate request warning"
    }
   ]
  },
  {
   "title": "P95 Bulk Size/Queued Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(elasticsearch_bulk_processor_bulk_size_bucket{service=\"$service\"}[1m])) by (le))*1000",
     "legendFormat": "bulk size"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(elasticsearch_bulk_processor_queued_requests_bucket{service=\"$service\"}[1m])) by (le))*1000",
     "legendFormat": "queued requests"
    }
   ]
  },
  {
   "title": "P95 Total Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(elasticsearch_bulk_processor_request_latency_bucket{service=\"$service\"}[1m])) by (le))",
     "legendFormat": "request latency"
    }
   ]
  },
  {
   "title": "P95 WaitAdd/WaitStart/Commit Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(elasticsearch_bulk_processor_wait_add_latency_bucket{service=\"$service\"}[1m])) by (le))",
     "legendFormat": "wait add latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(elasticsearch_bulk_processor_wait_start_latency_bucket{service=\"$service\"}[1m])) by (le))",
     "legendFormat": "wait start latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(elasticsearch_bulk_processor_commit_latency_bucket{service=\"$service\"}[1m])) by (le))",
     "legendFormat": "commit latency"
    }
   ]
  },
  {
   "title": "Elasticsearch miscellaneous",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 },
   "collapsed": true,
   "panels": [
    {
     "title": "Doc Generate/Parse Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(elasticsearch_document_parse_failures_counter{service=\"$service\"}[1m]))",
       "legendFormat": "doc parse errors"
      },
      {
       "expr": "sum (rate(elasticsearch_document_generate_failures_counter{service=\"$service\"}[1m]))",
       "legendFormat": "doc generate errors"
      }
     ]
    },
    {
     "title": "Add Search Attributes Workflow",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "add_search_attributes_workflow_success{service=\"$service\"}",
       "legendFormat": "success"
      },
      {
       "expr": "add_search_attributes_workflow_failure{service=\"$service\"}",
       "legendFormat": "errors"
      },
      {
       "expr": "add_search_attributes_failures{service=\"$service\"}",
       "legendFormat": "activity errors"
      }
     ]
    }
   ]
  }
 ]
}