# This file was auto-generated by Fern from our API Definition.

import typing

AgentToolsRouteListRequestSortBy = typing.Union[
    typing.Literal["created_at", "updated_at", "deleted_at"], typing.Any
]
