# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ChatCompletionResponseFormatType(str, enum.Enum):
    """
    The format of the response
    """

    TEXT = "text"
    JSON_OBJECT = "json_object"

    def visit(
        self,
        text: typing.Callable[[], T_Result],
        json_object: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is ChatCompletionResponseFormatType.TEXT:
            return text()
        if self is ChatCompletionResponseFormatType.JSON_OBJECT:
            return json_object()
