# This file was auto-generated by Fern from our API Definition.

import typing

from .entries_input_chat_ml_message_content_item import (
    EntriesInputChatMlMessageContentItem,
)

EntriesInputChatMlMessageContent = typing.Union[
    str, typing.List[str], typing.List[EntriesInputChatMlMessageContentItem]
]
