# This file was auto-generated by Fern from our API Definition.

import typing

EntriesChatMlRole = typing.Union[
    typing.Literal[
        "user",
        "assistant",
        "system",
        "function",
        "function_response",
        "function_call",
        "auto",
    ],
    typing.Any,
]
