# This file was auto-generated by Fern from our API Definition.

import typing

from .entry_content_item_item import EntryContentItemItem
from .tools_chosen_tool_call import ToolsChosenToolCall
from .tools_tool import ToolsTool
from .tools_tool_response import ToolsToolResponse

EntryContentItem = typing.Union[
    typing.List[EntryContentItemItem],
    ToolsTool,
    ToolsChosenToolCall,
    str,
    ToolsToolResponse,
]
