# This file was auto-generated by Fern from our API Definition.

import typing

from .entries_chat_ml_image_content_part import EntriesChatMlImageContentPart
from .entries_chat_ml_text_content_part import EntriesChatMlTextContentPart
from .entries_image_detail import EntriesImageDetail
from .entries_image_url import EntriesImageUrl
from .entries_input_chat_ml_message_content_item import (
    EntriesInputChatMlMessageContentItem,
)

EntriesInputChatMlMessageContent = typing.Union[
    str, typing.List[str], typing.List[EntriesInputChatMlMessageContentItem]
]
