# This file was auto-generated by Fern from our API Definition.

import typing

from .entries_entry_content_item_item import EntriesEntryContentItemItem
from .tools_chosen_tool_call import ToolsChosenToolCall
from .tools_tool import ToolsTool
from .tools_tool_response import ToolsToolResponse

EntriesEntryContentItem = typing.Union[
    typing.List[EntriesEntryContentItemItem],
    ToolsTool,
    ToolsChosenToolCall,
    str,
    ToolsToolResponse,
]
