# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class EntriesChatMlRole(str, enum.Enum):
    """
    ChatML role (system|assistant|user|function_call|function|function_response|auto)
    """

    USER = "user"
    AGENT = "agent"
    SYSTEM = "system"
    FUNCTION = "function"
    FUNCTION_RESPONSE = "function_response"
    FUNCTION_CALL = "function_call"
    AUTO = "auto"

    def visit(
        self,
        user: typing.Callable[[], T_Result],
        agent: typing.Callable[[], T_Result],
        system: typing.Callable[[], T_Result],
        function: typing.Callable[[], T_Result],
        function_response: typing.Callable[[], T_Result],
        function_call: typing.Callable[[], T_Result],
        auto: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is EntriesChatMlRole.USER:
            return user()
        if self is EntriesChatMlRole.AGENT:
            return agent()
        if self is EntriesChatMlRole.SYSTEM:
            return system()
        if self is EntriesChatMlRole.FUNCTION:
            return function()
        if self is EntriesChatMlRole.FUNCTION_RESPONSE:
            return function_response()
        if self is EntriesChatMlRole.FUNCTION_CALL:
            return function_call()
        if self is EntriesChatMlRole.AUTO:
            return auto()
