# This file was auto-generated by Fern from our API Definition.

import typing

ExecutionStatus = typing.Union[
    typing.Literal[
        "queued",
        "starting",
        "running",
        "awaiting_input",
        "succeeded",
        "failed",
        "cancelled",
    ],
    typing.Any,
]
