# This file was auto-generated by Fern from our API Definition.

import typing

ExecutionsTransitionType = typing.Union[
    typing.Literal["finish", "wait", "error", "step", "cancelled"], typing.Any
]
