# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.datetime_utils import serialize_datetime
from .common_uuid import CommonUuid
from .executions_execution_status import ExecutionsExecutionStatus

try:
    import pydantic.v1 as pydantic  # type: ignore
except ImportError:
    import pydantic  # type: ignore


class ExecutionsExecution(pydantic.BaseModel):
    task_id: CommonUuid = pydantic.Field(
        description="The ID of the task that the execution is running"
    )
    status: ExecutionsExecutionStatus = pydantic.Field(
        description="The status of the execution"
    )
    input: typing.Dict[str, typing.Any] = pydantic.Field(
        description="The input to the execution"
    )
    created_at: dt.datetime = pydantic.Field(
        description="When this resource was created as UTC date-time"
    )
    updated_at: dt.datetime = pydantic.Field(
        description="When this resource was updated as UTC date-time"
    )
    id: CommonUuid

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {
            "by_alias": True,
            "exclude_unset": True,
            **kwargs,
        }
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {
            "by_alias": True,
            "exclude_unset": True,
            **kwargs,
        }
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        json_encoders = {dt.datetime: serialize_datetime}
