# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.datetime_utils import serialize_datetime
from ..core.pydantic_utilities import deep_union_pydantic_dicts, pydantic_v1
from .common_py_expression import CommonPyExpression
from .tasks_base_workflow_step import TasksBaseWorkflowStep
from .tasks_if_else_workflow_step_else import TasksIfElseWorkflowStepElse
from .tasks_if_else_workflow_step_then import TasksIfElseWorkflowStepThen


class TasksIfElseWorkflowStep(TasksBaseWorkflowStep):
    if_: CommonPyExpression = pydantic_v1.Field(alias="if")
    """
    The condition to evaluate
    """

    then: TasksIfElseWorkflowStepThen = pydantic_v1.Field()
    """
    The steps to run if the condition is true
    """

    else_: TasksIfElseWorkflowStepElse = pydantic_v1.Field(alias="else")
    """
    The steps to run if the condition is false
    """

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {
            "by_alias": True,
            "exclude_unset": True,
            **kwargs,
        }
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults_exclude_unset: typing.Any = {
            "by_alias": True,
            "exclude_unset": True,
            **kwargs,
        }
        kwargs_with_defaults_exclude_none: typing.Any = {
            "by_alias": True,
            "exclude_none": True,
            **kwargs,
        }

        return deep_union_pydantic_dicts(
            super().dict(**kwargs_with_defaults_exclude_unset),
            super().dict(**kwargs_with_defaults_exclude_none),
        )

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True
        extra = pydantic_v1.Extra.allow
        json_encoders = {dt.datetime: serialize_datetime}
