# This file was auto-generated by Fern from our API Definition.

import typing

from .entries_input_chat_ml_message import EntriesInputChatMlMessage

TasksPromptStepPrompt = typing.Union[str, typing.List[EntriesInputChatMlMessage]]
