# This file was auto-generated by Fern from our API Definition.

import typing

from .tasks_prompt_step_settings_agent import TasksPromptStepSettingsAgent
from .tasks_prompt_step_settings_frequency_penalty import (
    TasksPromptStepSettingsFrequencyPenalty,
)
from .tasks_prompt_step_settings_preset import TasksPromptStepSettingsPreset

TasksPromptStepSettings = typing.Union[
    TasksPromptStepSettingsPreset,
    TasksPromptStepSettingsFrequencyPenalty,
    TasksPromptStepSettingsAgent,
]
