/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const JulepApiEnvironment = {
    Default: "https://api-alpha.julep.ai",
} as const;

export type JulepApiEnvironment = typeof JulepApiEnvironment.Default;
