/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare const JulepApiEnvironment: {
  readonly Default: "https://api-alpha.julep.ai";
};
export declare type JulepApiEnvironment = typeof JulepApiEnvironment.Default;
