/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { Chat_BaseChatOutput } from "./Chat_BaseChatOutput";
import type { Common_uuid } from "./Common_uuid";
import type { Entries_ChatMLRole } from "./Entries_ChatMLRole";
import type { Tools_ChosenApiCall } from "./Tools_ChosenApiCall";
import type { Tools_ChosenFunctionCall } from "./Tools_ChosenFunctionCall";
import type { Tools_ChosenIntegrationCall } from "./Tools_ChosenIntegrationCall";
import type { Tools_ChosenSystemCall } from "./Tools_ChosenSystemCall";
/**
 * The output returned by the model. Note that, depending on the model provider, they might return more than one message.
 */
export type Chat_MultipleChatOutput = Chat_BaseChatOutput & {
  readonly messages: Array<{
    /**
     * The role of the message
     */
    role: Entries_ChatMLRole;
    /**
     * The content parts of the message
     */
    content: string | Array<string>;
    /**
     * Name
     */
    name?: string;
    /**
     * Tool calls generated by the model.
     */
    readonly tool_calls?: Array<
      | Tools_ChosenFunctionCall
      | Tools_ChosenIntegrationCall
      | Tools_ChosenSystemCall
      | Tools_ChosenApiCall
    > | null;
    /**
     * When this resource was created as UTC date-time
     */
    readonly created_at?: string;
    readonly id?: Common_uuid;
  }>;
};
