import "../../common";

using Common;

namespace Tools;


// // TODO: Implement these
// /** browserbase extension provider */
// model BrowserbaseExtensionIntegrationDef extends BaseBrowserbaseIntegrationDef {
//     /** The specific method of the integration to call */
//     method?: "create_extension" | "get_extension" | "delete_extension";

//     /** The arguments for the method */
//     arguments?: unknown;
// }
