/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface GetAgentAdditionalInfoRequest {
    /**
     *
     */
    limit?: number;
    /**
     *
     */
    offset?: number;
}
