/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface UpdateUserRequest {
    /** About the user */
    about?: string;
    /** Name of the user */
    name?: string;
}
