[tasks]
format = "ruff format"
lint = "ruff check"
typecheck = "ty check"
check = [
    "lint",
    "format",
    "typecheck",
]

[tasks.test]
env = { JULEP_CLI_TESTING = "true", PYTHONPATH = "{PYTHONPATH}:." }
cmd = "pytest tests/ -v"
