/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";
export declare const AdditionalInfo: core.serialization.ObjectSchema<serializers.AdditionalInfo.Raw, JulepApi.AdditionalInfo>;
export declare namespace AdditionalInfo {
    interface Raw {
        title: string;
        content: string;
        id: string;
    }
}
