/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";
export declare const ChatMlMessageRole: core.serialization.Schema<serializers.ChatMlMessageRole.Raw, JulepApi.ChatMlMessageRole>;
export declare namespace ChatMlMessageRole {
    type Raw = "user" | "assistant" | "system" | "function_call";
}
