/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";
export declare const FunctionCallOption: core.serialization.ObjectSchema<serializers.FunctionCallOption.Raw, JulepApi.FunctionCallOption>;
export declare namespace FunctionCallOption {
    interface Raw {
        name: string;
    }
}
