/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";
export declare const GetAgentMemoriesResponse: core.serialization.ObjectSchema<serializers.GetAgentMemoriesResponse.Raw, JulepApi.GetAgentMemoriesResponse>;
export declare namespace GetAgentMemoriesResponse {
    interface Raw {
        items?: serializers.Memory.Raw[] | null;
    }
}
