/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";
export declare const InputChatMlMessage: core.serialization.ObjectSchema<serializers.InputChatMlMessage.Raw, JulepApi.InputChatMlMessage>;
export declare namespace InputChatMlMessage {
    interface Raw {
        role: serializers.InputChatMlMessageRole.Raw;
        content: string;
        name?: string | null;
        continue?: boolean | null;
    }
}
