/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";
export declare const ResourceUpdatedResponse: core.serialization.ObjectSchema<serializers.ResourceUpdatedResponse.Raw, JulepApi.ResourceUpdatedResponse>;
export declare namespace ResourceUpdatedResponse {
    interface Raw {
        id: string;
        updated_at: string;
    }
}
