name: julep-analytics

services:
  analytics:
    image: julepai/analytics:${TAG:-dev}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: julep-analytics
    profiles:
      - multi-tenant
    environment:
      # Metabase application database (for storing Metabase's own data)
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: ${MEMORY_STORE_PASSWORD:-julep_secure_password}
      MB_DB_HOST: memory-store
      
      # Metabase settings
      MB_SITE_URL: https://${JULEP_HOST:-localhost}/analytics
      MB_SITE_NAME: "Julep Analytics"
      MB_APPLICATION_NAME: "Julep Analytics"
      
      # AIDEV-NOTE: Metabase configured to use same postgres instance as agents-api
    ports:
      - "3001:3000"  # Expose on different port to avoid conflicts
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      memory-store:
        condition: service_healthy