"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChatSettingsPreset = void 0;
exports.ChatSettingsPreset = {
  ProblemSolving: "problem_solving",
  Conversational: "conversational",
  Fun: "fun",
  Prose: "prose",
  Creative: "creative",
  Business: "business",
  Deterministic: "deterministic",
  Code: "code",
  Multilingual: "multilingual",
};
