/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Current state (one of: pending, in_progress, retrying, succeeded, aborted, failed)
 */
export declare type JobStatusState =
  | "pending"
  | "in_progress"
  | "retrying"
  | "succeeded"
  | "aborted"
  | "failed"
  | "unknown";
export declare const JobStatusState: {
  readonly Pending: "pending";
  readonly InProgress: "in_progress";
  readonly Retrying: "retrying";
  readonly Succeeded: "succeeded";
  readonly Aborted: "aborted";
  readonly Failed: "failed";
  readonly Unknown: "unknown";
};
