/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Whether the suggestion is for the `agent` or a `user`
 */
export declare type SuggestionTarget = "user" | "agent";
export declare const SuggestionTarget: {
  readonly User: "user";
  readonly Agent: "agent";
};
