[tasks]
format = "ruff format"
lint = "ruff check"
typecheck = "pyright --threads 8 --skipunannotated julep_cli"
check = [
    "lint",
    "format",
    "typecheck",
]

[tasks.test]
env = { JULEP_CLI_TESTING = "true", PYTHONPATH = "{PYTHONPATH}:." }
cmd = "ward test --exclude .venv"
