import "./endpoints.tsp";
import "./models.tsp";
import "./anthropic.tsp";
import "./brave.tsp";
import "./email.tsp";
import "./spider.tsp";
import "./weather.tsp";
import "./wikipedia.tsp";
import "./browserbase";
import "./remote_browser.tsp";
import "./llama_parse.tsp";
import "./ffmpeg.tsp";
import "./cloudinary.tsp";
import "./arxiv.tsp";
import "./unstructured.tsp";
import "./algolia.tsp";
import "./google_sheets.tsp";

namespace Tools;

//
// TOOLS
//