/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         situation: "situation"
 *     }
 */
export interface UpdateSessionRequest {
  /** Updated situation for this session */
  situation: string;
}
