name: open-responses

include:
  - ../src/agents-api/docker-compose-api.yml
  - ../memory-store/docker-compose.yml
  - ../integrations-service/docker-compose.yml
  # - ../src/llm-proxy/docker-compose.yml
