emit:
  - "@typespec/openapi3"
  - "@typespec/http-client-python"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{output-dir}/schema"
    openapi-versions:
      - 3.1.0
  "@typespec/http-client-python":
    emitter-output-dir: "{output-dir}/clients/python"
