version: '3.8'

services:
  postgraphile:
    image: graphile/postgraphile:latest
    profiles:
      - multi-tenant
    ports:
      - "5000:5000"
    command: [
      "-c", "${DATABASE_URL}", 
      "--watch", 
      "--enhance-graphiql", 
      "--subscriptions", 
      "--dynamic-json", 
      "--retry-on-init-fail", 
      "--no-setof-functions-contain-nulls", 
      "--no-ignore-rbac", 
      "--extended-errors", "errcode", 
      "--enable-query-batching", 
      "--allow-explain", 
      "--legacy-relations", "omit",
      "--cors",
    ]
    environment:
      DATABASE_URL: ${PG_DSN:-postgres://postgres:postgres@memory-store:5432/postgres?sslmode=disable}
      # JWT_SECRET removed