import "./endpoints.tsp";
import "./base.tsp";
import "./functions.tsp";
import "./integrations.tsp";
import "./system.tsp";
import "./api_call.tsp";
import "./tool_definitions.tsp";
import "./anthropic.tsp";
import "./brave.tsp";
import "./email.tsp";
import "./spider.tsp";
import "./weather.tsp";
import "./wikipedia.tsp";
import "./browserbase";
import "./remote_browser.tsp";
import "./llama_parse.tsp";
import "./ffmpeg.tsp";
import "./cloudinary.tsp";
import "./arxiv.tsp";
import "./unstructured.tsp";
import "./algolia.tsp";

namespace Tools;

//
// TOOLS
//