/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../..";
import * as JulepApi from "../../../api";
import * as core from "../../../core";
export declare const CreateUserRequest: core.serialization.Schema<
  serializers.CreateUserRequest.Raw,
  JulepApi.CreateUserRequest
>;
export declare namespace CreateUserRequest {
  interface Raw {
    name?: string | null;
    about?: string | null;
    docs?: serializers.CreateDoc.Raw[] | null;
  }
}
