BEGIN;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM postgraphile;
ALTER TABLE developers DISABLE ROW LEVEL SECURITY;
ALTER TABLE agents DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE files DISABLE ROW LEVEL SECURITY;
ALTER TABLE file_owners DISABLE ROW LEVEL SECURITY;
ALTER TABLE docs DISABLE ROW LEVEL SECURITY;
ALTER TABLE doc_owners DISABLE ROW LEVEL SECURITY;
ALTER TABLE tools DISABLE ROW LEVEL SECURITY;
ALTER TABLE sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE session_lookup DISABLE ROW LEVEL SECURITY;
ALTER TABLE tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE workflows DISABLE ROW LEVEL SECURITY;
ALTER TABLE executions DISABLE ROW LEVEL SECURITY;
ALTER TABLE transitions DISABLE ROW LEVEL SECURITY;
ALTER TABLE temporal_executions_lookup DISABLE ROW LEVEL SECURITY;
ALTER TABLE entries DISABLE ROW LEVEL SECURITY;
ALTER TABLE entry_relations DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS access_users ON postgraphile_auth.users;
DROP POLICY access_developers_policy ON developers;
DROP POLICY access_agents_policy ON agents;
DROP POLICY access_users_policy ON users;
DROP POLICY access_files_policy ON files;
DROP POLICY access_file_owners_policy ON file_owners;
DROP POLICY access_docs_policy ON docs;
DROP POLICY access_doc_owners_policy ON doc_owners;
DROP POLICY access_tools_policy ON tools;
DROP POLICY access_sessions_policy ON sessions;
DROP POLICY access_session_lookup_policy ON session_lookup;
DROP POLICY access_tasks_policy ON tasks;
DROP POLICY access_workflows_policy ON workflows;
DROP POLICY access_executions_policy ON executions;
DROP POLICY access_transitions_policy ON transitions;
DROP POLICY access_temporal_executions_lookup_policy ON temporal_executions_lookup;
DROP POLICY access_entries_policy ON entries;
DROP POLICY access_entry_relations_policy ON entry_relations;
DROP TABLE IF EXISTS postgraphile_auth.users;
DROP FUNCTION IF EXISTS authenticate;
DROP FUNCTION current_developer_id;
DROP FUNCTION current_developer_id_by_transition_id;
DROP FUNCTION current_developer_id_by_execution_id;
DROP FUNCTION current_developer_id_by_session_id;
DROP TYPE IF EXISTS jwt_token;
DROP ROLE IF EXISTS postgraphile;
DROP ROLE IF EXISTS no_access_role;
DROP EXTENSION IF EXISTS pgcrypto;
DROP SCHEMA IF EXISTS postgraphile_auth;
COMMIT;