# generated by datamodel-codegen:
#   filename:  openapi-0.4.0.yaml

from __future__ import annotations

from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class ChosenToolCall(BaseModel):
    """
    The response tool value generated by the model
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal["function", "integration", "system", "api_call"]
    """
    Whether this tool is a `function`, `api_call`, `system` etc. (Only `function` tool supported right now)
    """
    function: FunctionCallOption | None = None
    id: Annotated[UUID, Field(json_schema_extra={"readOnly": True})]


class CreateToolRequest(BaseModel):
    """
    Payload for creating a tool
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Annotated[str, Field(max_length=40, pattern="^[^\\W0-9]\\w*$")]
    """
    Name of the tool (must be unique for this agent and a valid python identifier string )
    """
    function: FunctionDef | None = None
    """
    The function to call
    """
    integration: IntegrationDef | None = None
    system: SystemDef | None = None


class FunctionCallOption(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    """
    The name of the function
    """


class FunctionDef(BaseModel):
    """
    Function definition
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Any | None = None
    """
    DO NOT USE: This will be overriden by the tool name. Here only for compatibility reasons.
    """
    description: str | None = None
    """
    Description of the function
    """
    parameters: dict[str, Any] | None = None
    """
    The parameters the function accepts
    """


class IntegrationDef(BaseModel):
    """
    Integration definition
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    provider: (
        Literal[
            "dummy",
            "hacker_news",
            "weather",
            "wikipedia",
            "spider",
            "brave",
            "browserbase",
        ]
        | str
    )
    """
    The provider of the integration
    """
    method: str | None = None
    """
    The specific method of the integration to call
    """
    description: str | None = None
    """
    Optional description of the integration
    """
    setup: dict[str, Any] | None = None
    """
    The setup parameters the integration accepts
    """
    arguments: dict[str, Any] | None = None
    """
    The arguments to pre-apply to the integration call
    """


class IntegrationDefUpdate(BaseModel):
    """
    Integration definition
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    provider: (
        Literal[
            "dummy",
            "hacker_news",
            "weather",
            "wikipedia",
            "spider",
            "brave",
            "browserbase",
        ]
        | str
        | None
    ) = None
    """
    The provider of the integration
    """
    method: str | None = None
    """
    The specific method of the integration to call
    """
    description: str | None = None
    """
    Optional description of the integration
    """
    setup: dict[str, Any] | None = None
    """
    The setup parameters the integration accepts
    """
    arguments: dict[str, Any] | None = None
    """
    The arguments to pre-apply to the integration call
    """


class NamedToolChoice(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    function: FunctionCallOption | None = None


class PatchToolRequest(BaseModel):
    """
    Payload for patching a tool
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Annotated[str | None, Field(None, max_length=40, pattern="^[^\\W0-9]\\w*$")]
    """
    Name of the tool (must be unique for this agent and a valid python identifier string )
    """
    function: FunctionDef | None = None
    """
    The function to call
    """
    integration: IntegrationDefUpdate | None = None
    system: SystemDefUpdate | None = None


class SystemDef(BaseModel):
    """
    System definition
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    call: str
    """
    The name of the system call
    """
    description: str | None = None
    """
    Optional description of the system call
    """
    arguments: dict[str, Any] | None = None
    """
    The arguments to pre-apply to the system call
    """


class SystemDefUpdate(BaseModel):
    """
    System definition
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    call: str | None = None
    """
    The name of the system call
    """
    description: str | None = None
    """
    Optional description of the system call
    """
    arguments: dict[str, Any] | None = None
    """
    The arguments to pre-apply to the system call
    """


class Tool(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Annotated[str, Field(max_length=40, pattern="^[^\\W0-9]\\w*$")]
    """
    Name of the tool (must be unique for this agent and a valid python identifier string )
    """
    function: FunctionDef | None = None
    """
    The function to call
    """
    integration: IntegrationDef | None = None
    system: SystemDef | None = None
    created_at: Annotated[AwareDatetime, Field(json_schema_extra={"readOnly": True})]
    """
    When this resource was created as UTC date-time
    """
    updated_at: Annotated[AwareDatetime, Field(json_schema_extra={"readOnly": True})]
    """
    When this resource was updated as UTC date-time
    """
    id: Annotated[UUID, Field(json_schema_extra={"readOnly": True})]


class ToolResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: UUID
    output: dict[str, Any]
    """
    The output of the tool
    """


class UpdateToolRequest(BaseModel):
    """
    Payload for updating a tool
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Annotated[str, Field(max_length=40, pattern="^[^\\W0-9]\\w*$")]
    """
    Name of the tool (must be unique for this agent and a valid python identifier string )
    """
    function: FunctionDef | None = None
    """
    The function to call
    """
    integration: IntegrationDef | None = None
    system: SystemDef | None = None


class ChosenFunctionCall(ChosenToolCall):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal["function"] = "function"
    function: FunctionCallOption
    """
    The function to call
    """
