emit:
  - "@typespec/openapi3"

options:
  "@typespec/openapi3":
    file-type: yaml
    output-file: "openapi-{version}.yaml"
    new-line: lf
    omit-unreachable-types: true
    # openapi-versions: ["3.1.0"]
