/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../..";
import * as JulepApi from "../../../api";
import * as core from "../../../core";
export declare const ChatInput: core.serialization.Schema<
  serializers.ChatInput.Raw,
  JulepApi.ChatInput
>;
export declare namespace ChatInput {
  interface Raw
    extends serializers.ChatInputData.Raw,
      serializers.ChatSettings.Raw,
      serializers.MemoryAccessOptions.Raw {}
}
