version: '3.8'

services:
  unleash-db:
    image: postgres:16
    profiles: ["feature-flags"]
    environment:
      POSTGRES_DB: ${UNLEASH_DB_NAME:-unleash}
      POSTGRES_USER: ${UNLEASH_DB_USER:-unleash}
      POSTGRES_PASSWORD: ${UNLEASH_DB_PASSWORD:-unleash_password}
    volumes:
      - unleash_db_data:/var/lib/postgresql/data
    ports:
      # Host port 5433 maps to container port 5432
      - "${UNLEASH_DB_PORT:-5433}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${UNLEASH_DB_USER:-unleash}"]
      interval: 10s
      timeout: 5s
      retries: 5

  unleash:
    image: unleashorg/unleash-server:latest
    profiles: ["feature-flags"]
    environment:
      DATABASE_URL: postgres://${UNLEASH_DB_USER:-unleash}:${UNLEASH_DB_PASSWORD:-unleash_password}@unleash-db:5432/${UNLEASH_DB_NAME:-unleash}
      DATABASE_SSL: "false"
      LOG_LEVEL: ${UNLEASH_LOG_LEVEL:-info}
      INIT_FRONTEND_API_TOKENS: ${UNLEASH_FRONTEND_TOKEN:-default:development.unleash-insecure-frontend-api-token}
      INIT_CLIENT_API_TOKENS: ${UNLEASH_API_TOKEN:-default:development.unleash-insecure-api-token}
      INIT_ADMIN_API_TOKENS: ${UNLEASH_ADMIN_TOKEN:-*:*.unleash-insecure-admin-api-token}
      UNLEASH_URL: ${UNLEASH_URL:-http://localhost:4242}
      AUTH_TYPE: ${UNLEASH_AUTH_TYPE:-open-source}
      AUTH_ENABLE_API_TOKEN: "true"
    ports:
      # Bind only to localhost - not publicly accessible
      - "127.0.0.1:${UNLEASH_PORT:-4242}:4242"
    depends_on:
      unleash-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4242/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  unleash_db_data:
    external: true 