/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as JulepApi from "../..";
/**
 * @example
 *     {
 *         accept: "application/json",
 *         responseFormat: {
 *             type: JulepApi.ChatSettingsResponseFormatType.Text
 *         },
 *         temperature: 1,
 *         topP: 1,
 *         messages: [{
 *                 role: JulepApi.InputChatMlMessageRole.User,
 *                 content: "string"
 *             }],
 *         tools: [{
 *                 type: JulepApi.ToolType.Function,
 *                 definition: {
 *                     name: "string",
 *                     parameters: {
 *                         "string": "string"
 *                     }
 *                 },
 *                 id: "string"
 *             }]
 *     }
 */
export interface ChatInput
  extends JulepApi.ChatInputData,
    JulepApi.ChatSettings,
    JulepApi.MemoryAccessOptions {}
