/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as JulepApi from "../..";
/**
 * @example
 *     {}
 */
export interface CreateUserRequest {
  /** Name of the user */
  name?: string;
  /** About the user */
  about?: string;
  /** List of additional info about user */
  additionalInformation?: JulepApi.CreateAdditionalInfoRequest[];
}
