/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         query: "string"
 *     }
 */
export interface GetAgentMemoriesRequest {
  /**
   *
   */
  query: string;
  /**
   * episode, belief, entity
   */
  types?: string | string[];
  /**
   *
   */
  userId?: string;
  /**
   *
   */
  limit?: number;
  /**
   *
   */
  offset?: number;
}
