/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as JulepApi from "../..";
/**
 * @example
 *     {
 *         definition: {
 *             name: "name",
 *             parameters: {}
 *         }
 *     }
 */
export interface UpdateToolRequest {
  /** Function definition and parameters */
  definition: JulepApi.FunctionDef;
}
