{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default .Release.Name .Values.serviceAccount.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: julep-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
{{- end }}
