FROM migrate/migrate:latest

# Copy migrations from local directory
COPY migrations/ /migrations/

# Set the working directory
WORKDIR /

# Default command (can be overridden)
ENTRYPOINT ["migrate"]
CMD ["-path", "/migrations", "-database", "postgres://postgres:obviously_not_a_safe_password@memory-store:5432/postgres?sslmode=disable", "up"]
