global:
  scrape_interval: 5s
  scrape_timeout: 3s
  evaluation_interval: 5s
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []
scrape_configs:
- job_name: agents-api
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 3s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets: ['agents-api-multi-tenant:8080', 'worker:14000', 'temporal:15000']
