/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";

export const AgentDefaultSettings: core.serialization.ObjectSchema<
    serializers.AgentDefaultSettings.Raw,
    JulepApi.AgentDefaultSettings
> = core.serialization.object({
    frequencyPenalty: core.serialization.property("frequency_penalty", core.serialization.number().optional()),
    lengthPenalty: core.serialization.property("length_penalty", core.serialization.number().optional()),
    presencePenalty: core.serialization.property("presence_penalty", core.serialization.number().optional()),
    repetitionPenalty: core.serialization.property("repetition_penalty", core.serialization.number().optional()),
    temperature: core.serialization.number().optional(),
    topP: core.serialization.property("top_p", core.serialization.number().optional()),
});

export declare namespace AgentDefaultSettings {
    interface Raw {
        frequency_penalty?: number | null;
        length_penalty?: number | null;
        presence_penalty?: number | null;
        repetition_penalty?: number | null;
        temperature?: number | null;
        top_p?: number | null;
    }
}
