/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";
export declare const AgentDefaultSettingsPreset: core.serialization.Schema<
  serializers.AgentDefaultSettingsPreset.Raw,
  JulepApi.AgentDefaultSettingsPreset
>;
export declare namespace AgentDefaultSettingsPreset {
  type Raw =
    | "problem_solving"
    | "conversational"
    | "fun"
    | "prose"
    | "creative"
    | "business"
    | "deterministic"
    | "code"
    | "multilingual";
}
