/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";
export declare const Belief: core.serialization.ObjectSchema<
  serializers.Belief.Raw,
  JulepApi.Belief
>;
export declare namespace Belief {
  interface Raw {
    type: "belief";
    subject?: string | null;
    content: string;
    rationale?: string | null;
    weight: number;
    sentiment: number;
    created_at: string;
    id: string;
  }
}
