/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";

export const ChatMlMessage: core.serialization.ObjectSchema<serializers.ChatMlMessage.Raw, JulepApi.ChatMlMessage> =
    core.serialization.object({
        role: core.serialization.lazy(async () => (await import("..")).ChatMlMessageRole),
        content: core.serialization.string(),
        name: core.serialization.string().optional(),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        id: core.serialization.string(),
    });

export declare namespace ChatMlMessage {
    interface Raw {
        role: serializers.ChatMlMessageRole.Raw;
        content: string;
        name?: string | null;
        created_at: string;
        id: string;
    }
}
