/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";
export declare const ChatSettingsResponseFormatSchema: core.serialization.ObjectSchema<
  serializers.ChatSettingsResponseFormatSchema.Raw,
  JulepApi.ChatSettingsResponseFormatSchema
>;
export declare namespace ChatSettingsResponseFormatSchema {
  interface Raw {}
}
