/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";

export const CompletionUsage: core.serialization.ObjectSchema<
    serializers.CompletionUsage.Raw,
    JulepApi.CompletionUsage
> = core.serialization.object({
    completionTokens: core.serialization.property("completion_tokens", core.serialization.number()),
    promptTokens: core.serialization.property("prompt_tokens", core.serialization.number()),
    totalTokens: core.serialization.property("total_tokens", core.serialization.number()),
});

export declare namespace CompletionUsage {
    interface Raw {
        completion_tokens: number;
        prompt_tokens: number;
        total_tokens: number;
    }
}
