/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";

export const CreateToolRequestType: core.serialization.Schema<
    serializers.CreateToolRequestType.Raw,
    JulepApi.CreateToolRequestType
> = core.serialization.enum_(["function", "webhook"]);

export declare namespace CreateToolRequestType {
    type Raw = "function" | "webhook";
}
