/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";

export const CreateToolRequest: core.serialization.ObjectSchema<
    serializers.CreateToolRequest.Raw,
    JulepApi.CreateToolRequest
> = core.serialization.object({
    type: core.serialization.lazy(async () => (await import("..")).CreateToolRequestType),
    definition: core.serialization.lazyObject(async () => (await import("..")).FunctionDef),
});

export declare namespace CreateToolRequest {
    interface Raw {
        type: serializers.CreateToolRequestType.Raw;
        definition: serializers.FunctionDef.Raw;
    }
}
