/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";

export const Episode: core.serialization.ObjectSchema<serializers.Episode.Raw, JulepApi.Episode> =
    core.serialization.object({
        type: core.serialization.stringLiteral("episode"),
        subject: core.serialization.string().optional(),
        content: core.serialization.string(),
        weight: core.serialization.number(),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        lastAccessedAt: core.serialization.property("last_accessed_at", core.serialization.date()),
        happenedAt: core.serialization.property("happened_at", core.serialization.date()),
        duration: core.serialization.number().optional(),
        id: core.serialization.string(),
    });

export declare namespace Episode {
    interface Raw {
        type: "episode";
        subject?: string | null;
        content: string;
        weight: number;
        created_at: string;
        last_accessed_at: string;
        happened_at: string;
        duration?: number | null;
        id: string;
    }
}
