/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";
export declare const FunctionParameters: core.serialization.Schema<
  serializers.FunctionParameters.Raw,
  JulepApi.FunctionParameters
>;
export declare namespace FunctionParameters {
  type Raw = Record<string, any>;
}
