/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";

export const FunctionDef: core.serialization.ObjectSchema<serializers.FunctionDef.Raw, JulepApi.FunctionDef> =
    core.serialization.object({
        description: core.serialization.string().optional(),
        name: core.serialization.string(),
        parameters: core.serialization.lazy(async () => (await import("..")).FunctionParameters),
    });

export declare namespace FunctionDef {
    interface Raw {
        description?: string | null;
        name: string;
        parameters: serializers.FunctionParameters.Raw;
    }
}
