/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";
export declare const GetAgentDocsResponse: core.serialization.ObjectSchema<
  serializers.GetAgentDocsResponse.Raw,
  JulepApi.GetAgentDocsResponse
>;
export declare namespace GetAgentDocsResponse {
  interface Raw {
    items?: serializers.Doc.Raw[] | null;
  }
}
