/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";

export const GetAgentAdditionalInfoResponse: core.serialization.ObjectSchema<
    serializers.GetAgentAdditionalInfoResponse.Raw,
    JulepApi.GetAgentAdditionalInfoResponse
> = core.serialization.object({
    items: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("..")).AdditionalInfo))
        .optional(),
});

export declare namespace GetAgentAdditionalInfoResponse {
    interface Raw {
        items?: serializers.AdditionalInfo.Raw[] | null;
    }
}
