/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";

export const GetSuggestionsResponse: core.serialization.ObjectSchema<
    serializers.GetSuggestionsResponse.Raw,
    JulepApi.GetSuggestionsResponse
> = core.serialization.object({
    items: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("..")).Suggestion))
        .optional(),
});

export declare namespace GetSuggestionsResponse {
    interface Raw {
        items?: serializers.Suggestion.Raw[] | null;
    }
}
