/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";

export const InputChatMlMessageRole: core.serialization.Schema<
    serializers.InputChatMlMessageRole.Raw,
    JulepApi.InputChatMlMessageRole
> = core.serialization.enum_(["user", "assistant", "system", "function_call"]);

export declare namespace InputChatMlMessageRole {
    type Raw = "user" | "assistant" | "system" | "function_call";
}
