/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";

export const InputChatMlMessage: core.serialization.ObjectSchema<
    serializers.InputChatMlMessage.Raw,
    JulepApi.InputChatMlMessage
> = core.serialization.object({
    role: core.serialization.lazy(async () => (await import("..")).InputChatMlMessageRole),
    content: core.serialization.string(),
    name: core.serialization.string().optional(),
    continue: core.serialization.boolean().optional(),
});

export declare namespace InputChatMlMessage {
    interface Raw {
        role: serializers.InputChatMlMessageRole.Raw;
        content: string;
        name?: string | null;
        continue?: boolean | null;
    }
}
