/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";

export const ListAgentsResponse: core.serialization.ObjectSchema<
    serializers.ListAgentsResponse.Raw,
    JulepApi.ListAgentsResponse
> = core.serialization.object({
    items: core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).Agent)),
});

export declare namespace ListAgentsResponse {
    interface Raw {
        items: serializers.Agent.Raw[];
    }
}
