/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";

export const ListSessionsResponse: core.serialization.ObjectSchema<
    serializers.ListSessionsResponse.Raw,
    JulepApi.ListSessionsResponse
> = core.serialization.object({
    items: core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).Session)),
});

export declare namespace ListSessionsResponse {
    interface Raw {
        items: serializers.Session.Raw[];
    }
}
