/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";

export const MemoryAccessOptions: core.serialization.ObjectSchema<
    serializers.MemoryAccessOptions.Raw,
    JulepApi.MemoryAccessOptions
> = core.serialization.object({
    recall: core.serialization.boolean().optional(),
    remember: core.serialization.boolean().optional(),
});

export declare namespace MemoryAccessOptions {
    interface Raw {
        recall?: boolean | null;
        remember?: boolean | null;
    }
}
