/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";
export declare const Suggestion: core.serialization.ObjectSchema<
  serializers.Suggestion.Raw,
  JulepApi.Suggestion
>;
export declare namespace Suggestion {
  interface Raw {
    created_at?: string | null;
    target: serializers.SuggestionTarget.Raw;
    content: string;
    message_id: string;
    session_id: string;
  }
}
