/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";

export const Suggestion: core.serialization.ObjectSchema<serializers.Suggestion.Raw, JulepApi.Suggestion> =
    core.serialization.object({
        createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
        target: core.serialization.lazy(async () => (await import("..")).SuggestionTarget),
        content: core.serialization.string(),
        messageId: core.serialization.property("message_id", core.serialization.string()),
        sessionId: core.serialization.property("session_id", core.serialization.string()),
    });

export declare namespace Suggestion {
    interface Raw {
        created_at?: string | null;
        target: serializers.SuggestionTarget.Raw;
        content: string;
        message_id: string;
        session_id: string;
    }
}
