/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";
export declare const ToolChoiceOption: core.serialization.Schema<
  serializers.ToolChoiceOption.Raw,
  JulepApi.ToolChoiceOption
>;
export declare namespace ToolChoiceOption {
  type Raw = string;
}
