/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";

export const Tool: core.serialization.ObjectSchema<serializers.Tool.Raw, JulepApi.Tool> = core.serialization.object({
    type: core.serialization.lazy(async () => (await import("..")).ToolType),
    definition: core.serialization.lazyObject(async () => (await import("..")).FunctionDef),
    id: core.serialization.string(),
});

export declare namespace Tool {
    interface Raw {
        type: serializers.ToolType.Raw;
        definition: serializers.FunctionDef.Raw;
        id: string;
    }
}
