/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";
export declare const User: core.serialization.ObjectSchema<
  serializers.User.Raw,
  JulepApi.User
>;
export declare namespace User {
  interface Raw {
    name?: string | null;
    about?: string | null;
    created_at?: string | null;
    updated_at?: string | null;
    id: string;
  }
}
