/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";

export const User: core.serialization.ObjectSchema<serializers.User.Raw, JulepApi.User> = core.serialization.object({
    name: core.serialization.string().optional(),
    about: core.serialization.string().optional(),
    createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date().optional()),
    id: core.serialization.string(),
});

export declare namespace User {
    interface Raw {
        name?: string | null;
        about?: string | null;
        created_at?: string | null;
        updated_at?: string | null;
        id: string;
    }
}
