/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";
export declare const CreateDoc: core.serialization.ObjectSchema<
  serializers.CreateDoc.Raw,
  JulepApi.CreateDoc
>;
export declare namespace CreateDoc {
  interface Raw {
    title: string;
    content: string;
  }
}
