/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as JulepApi from "../../api";
import * as core from "../../core";
export declare const GetHistoryResponse: core.serialization.ObjectSchema<
  serializers.GetHistoryResponse.Raw,
  JulepApi.GetHistoryResponse
>;
export declare namespace GetHistoryResponse {
  interface Raw {
    items?: serializers.ChatMlMessage.Raw[] | null;
  }
}
