name: Bandit security check python agents-api
run-name: ${{ github.actor }} is checking the security of the code

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/agents-api/**'
  push:
    paths:
      - 'src/agents-api/**'

jobs:
  bandit_check:
    name: bandit check security of python code in agents-api
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Run Bandit scan
      uses: PyCQA/bandit-action@v1
      with:
        targets: "./src/agents-api/agents_api"
        confidence: high
        severity: high
