name: Test agents-api
run-name: ${{ github.actor }} is testing the code

on:
  pull_request:
    paths:
      - 'agents-api/**'
  push:
    paths:
      - 'agents-api/**'

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install libboost
        run: sudo apt-get install -y libboost-all-dev

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install Go migrate
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with: # Grab the latest version
          repo: golang-migrate/migrate

      - name: Set up python and install dependencies
        run: |
          cd agents-api
          uv python install
          uv sync --all-extras --dev

      - name: Run tests
        env:
          SECRETS_MASTER_KEY: ${{ secrets.SECRETS_MASTER_KEY }}
        run: |
          cd agents-api
          uv run poe test --fail-limit 3

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
