name: Test integrations-service
run-name: ${{ github.actor }} is testing the code

on:
  pull_request:
    paths:
      - 'modules/integrations-service/**'
  push:
    paths:
      - 'modules/integrations-service/**'

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up python and install dependencies
        run: |
          cd modules/integrations-service
          uv python install
          uv sync --all-extras --dev

      - name: Run tests
        run: |
          cd modules/integrations-service
          uv run poe test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
